# Generated by Django 4.2.5 on 2023-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('roll', models.BigIntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
